### ISSUE TITLE
jinja2 cannot be found when running ommprotol through mmsetup

### ISSUE THREAD

**Issue by JeanDidier** [insilichem/tangram#11]
Hi again, sorry to bug off...

When running MDs with openMM on a small peptide (pdb code 1ze7), I have the following problem:

```
Applications/Chimera.app/Contents/Resources/lib/python2.7/site-packages/matplotlib/axes.py:2369: UserWarning: Attempting to set identical left==right results
in singular transformations; automatically expanding.
left=1, right=1
  + 'left=%s, right=%s') % (left, right))
Traceback (most recent call last):
  File "/Applications/Chimera.app/Contents/Resources/share/chimera/tasks.py", line 179, in runStatusCB
    task.statusCBList[0]()
  File "/Applications/Chimera.app/Contents/Resources/share/chimera/SubprocessMonitor.py", line 165, in statusCB
    self.finished()
  File "/Applications/Chimera.app/Contents/Resources/share/chimera/SubprocessMonitor.py", line 201, in finished
    self._after(self._aborted)
  File "/Users/jeandi/tangram/lib/python2.7/site-packages/mmsetup/core.py", line 92, in _after_cb
    raise chimera.UserError(msg)
UserError: OMMProtocol calculation failed! Reason: ImportError: No module named jinja2
```
Thanks a lot!

**Comment by jaimergp** [comment]
Is that the only molecule failing? I had success with `1RFO` (first submodel only). Try to run that to discard any problems with the system (although it looks more of an installation issue).

**Comment by JeanDidier** [comment]
1rfo same thing
*****************************
Prof. Dr. Jean-Didier Maréchal
Associate Professor

Insilichem
Departament de Química
Universitat Autònoma de Barcelona
Edifici C.n.
08193 Cerdanyola (Barcelona)
Tel: +34.935814936
e-mail: JeanDidier.Marechal@uab.es
personal webpage: http://gent.uab.cat/jdidier
insilichem webpage: http://www.inslichem.com

**Comment by jaimergp** [comment]
Can you run these commands and send the output, please?

```
conda activate ~/tangram
conda list
```

**Comment by JeanDidier** [comment]
Sure, this is:
 packages in environment at /Users/jeandi/tangram:
#
# Name                    Version                   Build  Channel
ambermini                 16.16.0                       7    omnia
asn1crypto                0.24.0                py27_1003    conda-forge
babel                     2.6.0                      py_1    conda-forge
backports                 1.0                        py_2    conda-forge
backports.functools_lru_cache 1.5                        py_1    conda-forge
backports_abc             0.5                        py_1    conda-forge
biopython                 1.73             py27h1de35cc_0    conda-forge
blas                      1.1                    openblas    conda-forge
blosc                     1.15.1            h0a44026_1002    conda-forge
bzip2                     1.0.6             h1de35cc_1002    conda-forge
ca-certificates           2018.11.29           ha4d7672_0    conda-forge
cclib                     1.6.1                      py_0    conda-forge
certifi                   2018.11.29            py27_1000    conda-forge
cffi                      1.12.1           py27h342bebf_0    conda-forge
cftime                    1.0.3.4         py27h917ab60_1000    conda-forge
chardet                   3.0.4                 py27_1003    conda-forge
conda                     4.6.4                    py27_0    conda-forge
cryptography              2.5              py27hdbc3d79_1    conda-forge
curl                      7.64.0               heae2a1f_0    conda-forge
cycler                    0.10.0                     py_1    conda-forge
docutils                  0.14                  py27_1001    conda-forge
enum34                    1.1.6                 py27_1001    conda-forge
fftw3f                    3.3.4                         2    omnia
freetype                  2.9.1             h597ad8a_1005    conda-forge
functools32               3.2.3.2                    py_3    conda-forge
futures                   3.2.0                 py27_1000    conda-forge
gaudiview                 0.0.3                    py27_0
insilichem/label/dev
hdf4                      4.2.13            hf3c6af0_1002    conda-forge
hdf5                      1.10.4          nompi_h5598ddc_1105    conda-forge
idna                      2.8                   py27_1000    conda-forge
imagesize                 1.1.0                      py_0    conda-forge
ipaddress                 1.0.22                     py_1    conda-forge
jinja2                    2.10                       py_1    conda-forge
jpeg                      9c                h1de35cc_1001    conda-forge
kiwisolver                1.0.1           py27h04f5b5a_1002    conda-forge
krb5                      1.16.3            h24a3359_1000    conda-forge
libcurl                   7.64.0               h76de61e_0    conda-forge
libcxx                    7.0.0                h2d50403_2    conda-forge
libedit                   3.1.20170329      hcfe32e1_1001    conda-forge
libffi                    3.2.1             h0a44026_1005    conda-forge
libgcc                    4.8.5                         1    conda-forge
libgfortran               3.0.0                      1001    conda-forge
libnetcdf                 4.6.2             h6b88ef6_1001    conda-forge
libpng                    1.6.36            ha441bb4_1000    conda-forge
libssh2                   1.8.0             hf30b1f0_1003    conda-forge
libtangram                0.0.3                    py27_0
insilichem/label/dev
llvm-meta                 7.0.0                         0    conda-forge
markupsafe                1.1.0           py27h1de35cc_1000    conda-forge
matplotlib                2.2.3                    py27_1    conda-forge
matplotlib-base           2.2.3            py27hd64abcd_1    conda-forge
mdtraj                    1.9.1                    py27_0    omnia
nciplot                   git20170610          h60a02f8_2    insilichem
ncurses                   6.1               h0a44026_1002    conda-forge
netcdf4                   1.4.2           py27hd700958_1001    conda-forge
nomkl                     3.0                           0
numexpr                   2.6.9           py27h1702cab_1000    conda-forge
numpy                     1.15.4          py27_blas_openblashb06ca3d_0
[blas_openblas]  conda-forge
numpydoc                  0.8.0                      py_1    conda-forge
ommprotocol               0.1.11                   py27_0    insilichem
openblas                  0.3.3                ha44fe06_1    conda-forge
openmm                    7.3.0           py27_cuda92_rc_1    omnia
openmoltools              0.8.3                    py27_1    omnia
openssl                   1.0.2p            h1de35cc_1002    conda-forge
packaging                 19.0                       py_0    conda-forge
pandas                    0.24.1           py27h0a44026_0    conda-forge
parmed                    3.1.0                    py27_0    omnia
pdbfixer                  1.5                      py27_0    omnia
periodictable             1.5.0                      py_1    conda-forge
pip                       19.0.2                   py27_0    conda-forge
pmw                       2.0.1                 py27_1001    conda-forge
prody                     1.8.2            py27h6440ff4_0    insilichem
propka                    3.1.0                    py27_0    insilichem
pychimera                 0.2.7                    py27_0    insilichem
pycosat                   0.6.3           py27h1de35cc_1001    conda-forge
pycparser                 2.19                       py_0    conda-forge
pyopenssl                 19.0.0                   py27_0    conda-forge
pyparsing                 2.3.1                      py_0    conda-forge
pysocks                   1.6.8                 py27_1002    conda-forge
pytables                  3.4.4           py27h0af8b44_1004    conda-forge
python                    2.7.15            h61312e0_1006    conda-forge
python-dateutil           2.8.0                      py_0    conda-forge
pytz                      2018.9                     py_0    conda-forge
pyyaml                    3.13            py27h1de35cc_1001    conda-forge
rdkit                     2015.09.1                py27_3    omnia
readline                  7.0               hcfe32e1_1001    conda-forge
requests                  2.21.0                py27_1000    conda-forge
ruamel_yaml               0.15.71         py27h1de35cc_1000    conda-forge
scipy                     1.2.0           py27_blas_openblashb06ca3d_200
[blas_openblas]  conda-forge
setuptools                40.8.0                   py27_0    conda-forge
singledispatch            3.4.0.3               py27_1000    conda-forge
six                       1.12.0                py27_1000    conda-forge
snowballstemmer           1.2.1                      py_1    conda-forge
sphinxcontrib-websupport  1.1.0                      py_1    conda-forge
sqlite                    3.26.0            h1765d9f_1000    conda-forge
subprocess32              3.2.6                    py27_0    omnia
tangram                   0.0.7                    py27_0
file:///Users/travis/miniconda/conda-bld
tangram_bondorder         0.0.2                    py27_0
insilichem/label/dev
tangram_dummyatoms        0.0.2                    py27_0
insilichem/label/dev
tangram_mmsetup           0.0.2                    py27_0
insilichem/label/dev
tangram_nciplot           0.0.2                    py27_0
insilichem/label/dev
tangram_normalmodes       0.0.2                    py27_0
insilichem/label/dev
tangram_orbitraj          0.0.2                    py27_0
insilichem/label/dev
tangram_popmusicgui       0.0.2                    py27_0
insilichem/label/dev
tangram_propkagui         0.0.2                    py27_0
insilichem/label/dev
tangram_qmsetup           0.0.2                    py27_0
insilichem/label/dev
tangram_selection         0.0.2                    py27_0
insilichem/label/dev
tangram_snfg              0.0.2                    py27_0
insilichem/label/dev
tangram_subalign          0.0.2                    py27_0
insilichem/label/dev
tangram_vinarelaunch      0.0.2                    py27_0
insilichem/label/dev
tkintertable              1.1.2                    py27_0    insilichem
tornado                   5.1.1           py27h1de35cc_1000    conda-forge
tqdm                      4.31.1                     py_0    conda-forge
typing                    3.6.6                 py27_1000    conda-forge
urllib3                   1.24.1                py27_1000    conda-forge
wheel                     0.33.0                   py27_0    conda-forge
yaml                      0.1.7             h1de35cc_1001    conda-forge
zlib                      1.2.11            h1de35cc_1004    conda-forge
*****************************
Prof. Dr. Jean-Didier Maréchal
Associate Professor

Insilichem
Departament de Química
Universitat Autònoma de Barcelona
Edifici C.n.
08193 Cerdanyola (Barcelona)
Tel: +34.935814936
e-mail: JeanDidier.Marechal@uab.es
personal webpage: http://gent.uab.cat/jdidier
insilichem webpage: http://www.inslichem.com

**Comment by jaimergp** [comment]
`jinja2` is listed. What is the result of `which ommprotocol`? I am worried that you might a past installation hanging on `$PATH` and the GUI is calling that one instead of the one provided in the new Tangram environment.

**Comment by JeanDidier** [comment]
Sure, this is the answer of which
/Users/jeandi/tangram/bin/ommprotocol

*****************************
Prof. Dr. Jean-Didier Maréchal
Associate Professor

Insilichem
Departament de Química
Universitat Autònoma de Barcelona
Edifici C.n.
08193 Cerdanyola (Barcelona)
Tel: +34.935814936
e-mail: JeanDidier.Marechal@uab.es
personal webpage: http://gent.uab.cat/jdidier
insilichem webpage: http://www.inslichem.com

**Comment by jaimergp** [comment]
Hmmm, that _should_ be the value.

Let's see if Chimera has something to do... Open Tangram and then the IDLE. Execute these commands:

```
from distutils.spawn import find_executable
find_executable('ommprotocol')
```

**Comment by JeanDidier** [comment]
here it comes
'/Users/jeandi/tangram/bin/ommprotocol'

*****************************
Prof. Dr. Jean-Didier Maréchal
Associate Professor

Insilichem
Departament de Química
Universitat Autònoma de Barcelona
Edifici C.n.
08193 Cerdanyola (Barcelona)
Tel: +34.935814936
e-mail: JeanDidier.Marechal@uab.es
personal webpage: http://gent.uab.cat/jdidier
insilichem webpage: http://www.inslichem.com

**Comment by JeanDidier** [comment]
OK, the jinja2 apparently is not properly installing on macOs. I am not sure why.
