### ISSUE TITLE
different message 0.0.8 MAcOs MD

### ISSUE THREAD

**Issue by JeanDidier** [insilichem/tangram#13]
Hi,

I reinstalled everything and things have gone far smoother. But I ran MD on MacOs with pdb 1RFO and this is the message that pops up in the terminal:

objc[10862]: Class FIFinderSyncExtensionHost is implemented in both /System/Library/PrivateFrameworks/FinderKit.framework/Versions/A/FinderKit (0x7fff8bc8c210) and /System/Library/PrivateFrameworks/FileProvider.framework/OverrideBundles/FinderSyncCollaborationFileProviderOverride.bundle/Contents/MacOS/FinderSyncCollaborationFileProviderOverride (0x11721fdc8). One of the two will be used. Which one is undefined.

The reply log continues complaining:
/Applications/Chimera.app/Contents/Resources/lib/python2.7/site-packages/matplotlib/axes.py:2369: UserWarning: Attempting to set identical left==right results
in singular transformations; automatically expanding.
left=1, right=1
  + 'left=%s, right=%s') % (left, right))
Traceback (most recent call last):
  File "/Applications/Chimera.app/Contents/Resources/share/chimera/tasks.py", line 179, in runStatusCB
    task.statusCBList[0]()
  File "/Applications/Chimera.app/Contents/Resources/share/chimera/SubprocessMonitor.py", line 165, in statusCB
    self.finished()
  File "/Applications/Chimera.app/Contents/Resources/share/chimera/SubprocessMonitor.py", line 201, in finished
    self._after(self._aborted)
  File "/Users/jeandi/tangram/lib/python2.7/site-packages/mmsetup/core.py", line 92, in _after_cb
    raise chimera.UserError(msg)
UserError: OMMProtocol calculation failed! Reason: ImportError: No module named jinja2

**Comment by JeanDidier** [comment]
THE normal modes comes with the following, which I guess may be the same than the linux problem.

RuntimeError: module compiled against API version 0xa but this version of numpy is 0x7
/Users/jeandi/tangram/lib/python2.7/site-packages/scipy/__init__.py:115: UserWarning: Numpy 1.8.2 or above is recommended for this version of scipy (detected version 1.7.2)
  UserWarning)
RuntimeError: module compiled against API version 9 but this version of numpy is 7
RuntimeError: module compiled against API version 9 but this version of numpy is 7
ImportError Exception in Tk callback
  Function: <function activate at 0x115a5d668> (type: <type 'function'>)
  Module: <module 'chimera.extension.base' from '/Applications/Chimera.app/Contents/Resources/share/chimera/extension/base.pyc'> (line: 487)
  Args: ()
Traceback (innermost last):
  File "/Applications/Chimera.app/Contents/Resources/lib/python2.7/site-packages/Pmw/Pmw_1_3_3/lib/PmwBase.py", line 1747, in __call__
    return apply(self.func, args)
  File "/Applications/Chimera.app/Contents/Resources/share/chimera/extension/base.py", line 488, in activate
    e.menuActivate(cat)
  File "/Applications/Chimera.app/Contents/Resources/share/chimera/extension/base.py", line 91, in menuActivate
    self.activate()
  File "/Users/jeandi/tangram/lib/python2.7/site-packages/normalmodes/ChimeraExtension.py", line 23, in activate
    self.module('gui').showUI()
  File "/Applications/Chimera.app/Contents/Resources/share/chimera/extension/base.py", line 113, in module
    mod = __import__(fullName)
  File "/Users/jeandi/tangram/lib/python2.7/site-packages/normalmodes/gui.py", line 12, in <module>
    from core import Controller
  File "/Users/jeandi/tangram/lib/python2.7/site-packages/normalmodes/core.py", line 11, in <module>
    import prody
  File "/Users/jeandi/tangram/lib/python2.7/site-packages/prody/__init__.py", line 95, in <module>
    from . import dynamics
  File "/Users/jeandi/tangram/lib/python2.7/site-packages/prody/dynamics/__init__.py", line 242, in <module>
    from . import rtb
  File "/Users/jeandi/tangram/lib/python2.7/site-packages/prody/dynamics/rtb.py", line 12, in <module>
    from scipy import sparse
  File "/Users/jeandi/tangram/lib/python2.7/site-packages/scipy/sparse/__init__.py", line 231, in <module>
    from .csr import *
  File "/Users/jeandi/tangram/lib/python2.7/site-packages/scipy/sparse/csr.py", line 15, in <module>
    from ._sparsetools import csr_tocsc, csr_tobsr, csr_count_blocks, \
ImportError: numpy.core.multiarray failed to import

ImportError: numpy.core.multiarray failed to import

  File "/Users/jeandi/tangram/lib/python2.7/site-packages/scipy/sparse/csr.py", line 15, in <module>
    from ._sparsetools import csr_tocsc, csr_tobsr, csr_count_blocks, \

See reply log for Python traceback.

**Comment by JeanDidier** [comment]
Hi,

When running the subalign command line with two ligands in taladraw, chimera crashes and the terminal remains with
Fatal Python error: PyThreadState_Get: no current thread
Abort trap: 6

Thank you!

**Comment by jaimergp** [comment]
Using MacOS? I have only tested it on Linux (Ubuntu 18.10), so we should start with that and then see if we can use it on Mac.

**Comment by JeanDidier** [comment]
OK, do not worry. I'll go for Linux.

*****************************
Prof. Dr. Jean-Didier Maréchal
Associate Professor

Insilichem
Departament de Química
Universitat Autònoma de Barcelona
Edifici C.n.
08193 Cerdanyola (Barcelona)
Tel: +34.935814936
e-mail: JeanDidier.Marechal@uab.es
personal webpage: http://gent.uab.cat/jdidier
insilichem webpage: http://www.inslichem.com

**Comment by jaimergp** [comment]
Ok, I'll close this, since there were different problems mentioned. I've created one issue for each one. In the future, it'd be better if we stick to that (instead of having a misc report on a single issue). I'll create a GitHub issue template to address this, as well.

**Comment by JeanDidier** [comment]
OK, I'll stick to what you advise for the issues.

*****************************
Prof. Dr. Jean-Didier Maréchal
Associate Professor

Insilichem
Departament de Química
Universitat Autònoma de Barcelona
Edifici C.n.
08193 Cerdanyola (Barcelona)
Tel: +34.935814936
e-mail: JeanDidier.Marechal@uab.es
personal webpage: http://gent.uab.cat/jdidier
insilichem webpage: http://www.inslichem.com
