### ISSUE TITLE
Problem with taladraw in tangram 0.0.8

### ISSUE THREAD

**Issue by JeanDidier** [insilichem/tangram#16]
Hello,

I just installed tangram on my ubuntu box. Everything fine but the subalign sel #1 #2 methods best,com does not work in the command line when selecting two ligand for superposition. I have the following message in the reply log:

Error fixing styles: <type 'exceptions.KeyError'> <class Tkinter.Label at 0x7fb30b68d808>
Error fixing styles: <type 'exceptions.KeyError'> <class Tkinter.LabelFrame at 0x7fb30b68de20>
Error fixing styles: <type 'exceptions.AttributeError'> 'dict' object has no attribute 'configure'
Error fixing styles: <type 'exceptions.KeyError'> <class Tkinter.Frame at 0x7fb30b68d7a0>
! Could not obtain version info from https://api.github.com/repos/insilichem/tangram_taladraw/releases/latest
  Reason: HTTP Error 404: Not Found
RDKit must be installed to use this extension.

RDKit must be installed to use this extension.

**Comment by jaimergp** [comment]
(Please, try to use the issue template for bug reports, otherwise I will have to ask the same questions over and over again).

Installation method?

Also, open Tangram, then the IDLE, and try to `import rdkit`  there. Let's see what is missing. You might also need to review the paths that are added in "Favorites-Add to favorites/toolbar".

**Comment by JeanDidier** [comment]
Re. (Please, try to use the issue template for bug reports, otherwise I will have to ask the same questions over and over again).

OK, I'll do this (on the next one? or I resend you the thingy?)

The paths are fine.

Regards


>>> import rdkit
Traceback (most recent call last):
  File "<pyshell#1>", line 1, in <module>
    import rdkit
  File "/home/jeandi/miniconda3/envs/tangram/lib/python2.7/site-packages/rdkit/__init__.py", line 2, in <module>
    from .rdBase import rdkitVersion as __version__
ImportError: libboost_python27.so.1.68.0: cannot open shared object file: No such file or directory

**Comment by jaimergp** [comment]
I managed to reproduce the bug!

Apparently, rdkit is being installed off of `conda-forge` (and not the `rdkit` channel itself), which causes some problems.

I solved it by forcing it to use the `rdkit` channel. So in a nutshell (I see you are using the metapackage, nice!):

```
conda activate tangram
conda install -c rdkit rdkit
```

This should fix it :)

**Comment by jaimergp** [comment]
Btw, I have updated the docs to fix this bug (thanks!) and checked with a bare installation. Confirmed and fixed! Feel free to close this when you confirm it on your side, as well.
