### ISSUE TITLE
ImportError: No module named _chimera

### ISSUE THREAD

**Issue by Yagosangan** [insilichem/tangram#3]
Hi, I'm trying to install tangram suite in MacOS, I have MacOS 10.11.6 and Python 2.7.15

During the installation I get the following errors and warnings, though the install finishes.

``` shell
You are using pip version 10.0.1, however version 18.0 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
DEPRECATION: Dependency Links processing has been deprecated and will be removed in a future release.
cftime 1.0.0b1 requires cython, which is not installed.
plip 1.3.3 requires openbabel, which is not installed.
numpydoc 0.8.0 requires sphinx>=1.2.3, which is not installed.
Error while importing plipgui from /Users/Cacharra/tangram/lib/python2.7/site-packages:
Traceback (most recent call last):
  File "/Applications/Chimera.app/Contents/Resources/share/chimera/extension/base.py", line 351, in _importExtension
    __import__(module)
  File "/Users/Cacharra/tangram/lib/python2.7/site-packages/plipgui/ChimeraExtension.py", line 8, in <module>
    from plipgui.core import cmd_plip, cmd_unplip
  File "/Users/Cacharra/tangram/lib/python2.7/site-packages/plipgui/core.py", line 50, in <module>
    from plip.modules.preparation import PDBComplex
  File "/Users/Cacharra/tangram/lib/python2.7/site-packages/plip/modules/preparation.py", line 24, in <module>
    from detection import *
  File "/Users/Cacharra/tangram/lib/python2.7/site-packages/plip/modules/detection.py", line 24, in <module>
    from supplemental import *
  File "/Users/Cacharra/tangram/lib/python2.7/site-packages/plip/modules/supplemental.py", line 38, in <module>
    import pybel
ImportError: No module named pybel

```

But after the install, when I try to start tangram like this

``` shell
Last login: Mon Sep  3 22:23:41 on ttys000
(base) 192:~ Cacharra$ tangram

     _____  _    _   _  ____ ____      _    __  __
    |_   _|/ \  | \ | |/ ___|  _ \    / \  |  \/  |
      | | / _ \ |  \| | |  _| |_) |  / _ \ | |\/| |
      | |/ ___ \| |\  | |_| |  _ <  / ___ \| |  | |
      |_/_/   \_\_| \_|\____|_| \_\/_/   \_\_|  |_|

 Tangram suite -- https://github.com/insilichem/tangram

 Launching UCSF Chimera via pychimera...

Traceback (most recent call last):
  File "/Users/Cacharra/tangram/bin/pychimera", line 12, in <module>
    update_dict = pychimera.__main__.run()
  File "/Users/Cacharra/tangram/lib/python2.7/site-packages/pychimera/__main__.py", line 6, in run
    pychimera.main()
  File "/Users/Cacharra/tangram/lib/python2.7/site-packages/pychimera/core.py", line 333, in main
    enable_chimera(verbose=args.verbose, nogui=args.nogui)
  File "/Users/Cacharra/tangram/lib/python2.7/site-packages/pychimera/core.py", line 60, in enable_chimera
    import chimera
  File "/Applications/Chimera.app/Contents/Resources/share/chimera/__init__.py", line 16, in <module>
    from _chimera import BBox, Camera, Color, ColorGroup, DirectionalLight, LODControl, Lens, LensViewer, Light, Material, MaterialColor, Model, NoGuiViewer, OGLFont, OSLAbbreviation, OpenModels, OpenState, PathFinder, PixelMap, Plane, Point, PositionalLight, Selectable, SharedState, SpotLight, Sphere, Texture, TextureColor, TrackChanges, Vector, Viewer, X3DScene, Xform
ImportError: No module named _chimera
(base) 192:~ Cacharra$ 

```

**Comment by jaimergp** [comment]
Hi!

Thanks for showing interest in Tangram. Those warnings are expected and known. We are working to fix them, but they are not fatal. 

The `tangram` error is due to PyChimera, the library that tries to make UCSF Chimera with external Python libraries. I have added a fix to workaround this error. I don't have a Mac around, but this should update `pychimera` in your Tangram installation so you can try the fixed version (v0.2.5):

1. Activate the Tangram environment: `conda activate ~/tangram/` (or whatever path you chose in the installation)
2. Update pychimera to latest version: `pip install -U pychimera`.
3. Cross fingers and run `tangram` :D

Let me know if this works!

**Comment by Yagosangan** [comment]
Ok, now Chimera initializes when I run ```tangram``` and the previous error disappeared. However, I get this now:

```shell
from backports.configparser import (
ImportError: No module named backports.configparser
```

Thanks for the quick response, by the way!

**Comment by jaimergp** [comment]
Can you post the full traceback? `configparser` is not one of our dependencies, but might be a secondary one (ie, a dependency of one of our dependencies). It should be installed automatically during the wizard, but maybe you can fix it manually with either:

```
pip install -U configparser
```

or 

```
conda install configparser
```

**Comment by jaimergp** [comment]
Since no more info was provided and the original error was solved, I'll mark this as closed. Feel free to reopen again if needed.
